export const FETCH_WORKOUTS_API = '@@Workouts/FETCH_WORKOUTS_API';
export const FETCH_WORKOUTS_API_SUCCESS = '@@Workouts/FETCH_WORKOUTS_API_SUCCESS';
export const FETCH_WORKOUTS_API_ERROR = '@@Workouts/FETCH_WORKOUTS_API_FAILURE';

